package com.qiusuo.pair.data.mapper;

import com.qiusuo.pair.data.entity.Trade;
import com.qiusuo.pair.data.entity.TradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE
     *
     * @mbggenerated Sat Feb 28 14:38:54 CST 2015
     */
    int countByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE
     *
     * @mbggenerated Sat Feb 28 14:38:54 CST 2015
     */
    int deleteByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE
     *
     * @mbggenerated Sat Feb 28 14:38:54 CST 2015
     */
    int insert(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE
     *
     * @mbggenerated Sat Feb 28 14:38:54 CST 2015
     */
    int insertSelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE
     *
     * @mbggenerated Sat Feb 28 14:38:54 CST 2015
     */
    List<Trade> selectByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE
     *
     * @mbggenerated Sat Feb 28 14:38:54 CST 2015
     */
    int updateByExampleSelective(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE
     *
     * @mbggenerated Sat Feb 28 14:38:54 CST 2015
     */
    int updateByExample(@Param("record") Trade record, @Param("example") TradeExample example);
}