package com.qiusuo.pair.data.entity;

import java.math.BigDecimal;
import java.util.Date;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

public class Trade {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TRADE.USER_ID
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	@NotNull
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TRADE.CURRENCY_FROM
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	private String currencyFrom;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TRADE.CURRENCY_TO
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	private String currencyTo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TRADE.AMOUNT_SELL
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	private BigDecimal amountSell;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TRADE.AMOUNT_BUY
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	private BigDecimal amountBuy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TRADE.RATE
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	@Min(0)
	@Max(100)
	private BigDecimal rate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TRADE.TIME_PLACED
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	private Date timePlaced;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TRADE.ORIGINATING_COUNTRY
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	private String originatingCountry;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TRADE.USER_ID
	 *
	 * @return the value of TRADE.USER_ID
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TRADE.USER_ID
	 *
	 * @param userId
	 *            the value for TRADE.USER_ID
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TRADE.CURRENCY_FROM
	 *
	 * @return the value of TRADE.CURRENCY_FROM
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public String getCurrencyFrom() {
		return currencyFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TRADE.CURRENCY_FROM
	 *
	 * @param currencyFrom
	 *            the value for TRADE.CURRENCY_FROM
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public void setCurrencyFrom(String currencyFrom) {
		this.currencyFrom = currencyFrom == null ? null : currencyFrom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TRADE.CURRENCY_TO
	 *
	 * @return the value of TRADE.CURRENCY_TO
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public String getCurrencyTo() {
		return currencyTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TRADE.CURRENCY_TO
	 *
	 * @param currencyTo
	 *            the value for TRADE.CURRENCY_TO
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public void setCurrencyTo(String currencyTo) {
		this.currencyTo = currencyTo == null ? null : currencyTo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TRADE.AMOUNT_SELL
	 *
	 * @return the value of TRADE.AMOUNT_SELL
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public BigDecimal getAmountSell() {
		return amountSell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TRADE.AMOUNT_SELL
	 *
	 * @param amountSell
	 *            the value for TRADE.AMOUNT_SELL
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public void setAmountSell(BigDecimal amountSell) {
		this.amountSell = amountSell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TRADE.AMOUNT_BUY
	 *
	 * @return the value of TRADE.AMOUNT_BUY
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public BigDecimal getAmountBuy() {
		return amountBuy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TRADE.AMOUNT_BUY
	 *
	 * @param amountBuy
	 *            the value for TRADE.AMOUNT_BUY
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public void setAmountBuy(BigDecimal amountBuy) {
		this.amountBuy = amountBuy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TRADE.RATE
	 *
	 * @return the value of TRADE.RATE
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public BigDecimal getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TRADE.RATE
	 *
	 * @param rate
	 *            the value for TRADE.RATE
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TRADE.TIME_PLACED
	 *
	 * @return the value of TRADE.TIME_PLACED
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public Date getTimePlaced() {
		return timePlaced;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TRADE.TIME_PLACED
	 *
	 * @param timePlaced
	 *            the value for TRADE.TIME_PLACED
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public void setTimePlaced(Date timePlaced) {
		this.timePlaced = timePlaced;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TRADE.ORIGINATING_COUNTRY
	 *
	 * @return the value of TRADE.ORIGINATING_COUNTRY
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public String getOriginatingCountry() {
		return originatingCountry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TRADE.ORIGINATING_COUNTRY
	 *
	 * @param originatingCountry
	 *            the value for TRADE.ORIGINATING_COUNTRY
	 *
	 * @mbggenerated Sat Feb 28 14:38:54 CST 2015
	 */
	public void setOriginatingCountry(String originatingCountry) {
		this.originatingCountry = originatingCountry == null ? null
				: originatingCountry.trim();
	}
}